### ISSUE TITLE
BIOS option locations on AMI 5.14

### ISSUE THREAD

**Issue by plato79** [kingo132/GPD-Win-Max-Hackintosh#4]
I have updated BIOS to AMI 5.14... But this is more than what a normal motherboard BIOS has.. Could you explain where to find these options..

I could only find Intel (VMX) Virtualization Technology setting which I think is VT-d..

The others  I couldn't find where they are.

**Comment by kingo132** [comment]
I have never used this version of bios, so you may have to find it yourself. If your bios is complete, you can definitely find it. cfg-lock and Vt-d should be under cpu setting. Dvmt should be under video configuration. EHCI Hand-off should be under USB setting.
