### ISSUE TITLE
Dual booting to Windows

### ISSUE THREAD

**Issue by plato79** [kingo132/GPD-Win-Max-Hackintosh#7]
I think we have a problem here...

OpenCore is awful when dual booting.. The thing is when it makes changes to ACPI via .aml files, it changes them for all OSes.. So if I try to boot Windows from OC boot menu it gives ACPI BIOS ERROR. Currently only option I found to Dual Boot is switching "Windows Boot Manager" and "UEFI OS" from BIOS.

I found out in olden times, there was a fork of OpenCore from n-d-k which has an option to enable ACPI patches for only MacOSX, although as far as I can see that one is dead ( last update was for OpenCore 0.5.8 )

Another option is to write an if case in ACPI patches like this: https://www.reddit.com/r/hackintosh/comments/exyiq9/opencore_windows_acpi_injection/fger5xr?utm_source=share&utm_medium=web2x&context=3

I don't know if it will work or not but could you make this change and recompile AML files?

**Comment by kingo132** [comment]
hi, plato79, I have fixed the windows boot problem, see my changelog, use the newest version of my EFI, there won't be any problem when booting windows 10.
