### ISSUE TITLE
Some questions about compatibility with macOS Big Sur (11.5.2)

### ISSUE THREAD

**Issue by kanhuiji100** [kingo132/GPD-Win-Max-Hackintosh#8]
On macOS Big Sur (11.5.2), I need to update Lilu.kext, AirportItlwm.kext, IntelBluetoothFirmware.kext, IntelBluetoothInject.kext, and modify the enable of IntelBluetooth two kexts in config.plist to be set to true to enter System and make the wireless hardware work normally.
I don’t know if the original files in this project work properly in macOS Catalina, nor if the changes I made are compatible with macOS Catalina. So I would like to ask whether these changes can be merged into the EFI folder of this project, or an EFI for Big Sur can be created separately to save a copy.
All kexts mentioned in this issue can be downloaded from their corresponding github pages.

**Comment by kanhuiji100** [comment]
And after testing, macOS Big Sur before version 11.2 cannot drive the Bluetooth function in the intel AX200 network card with Bluetooth 5.1. The core specification is shown as Unknown (0xA). Can this be written in readme.md?

**Comment by kingo132** [comment]
hi, kanhuiji100, you can upgrade "Lilu.kext, AirportItlwm.kext, IntelBluetoothFirmware.kext, IntelBluetoothInject.kext" without any problem. And some people already have successfully installed Big Sur using my EFI without any problem, there are only AirportItlwm.kext needs to be replaced with Big Sur version, no need to upgrade other kexts, I think.
